image: docker:latest

services:
  - docker:dind

test:
  stage: test
  script:
    - apk add --no-cache bash
    - ./cicd/run_coverage.sh
    - ./cicd/run_analyze.sh
  artifacts:
    paths:
      - results/
