image: docker:latest

variables:
  # from: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

test:
  stage: test
  script:
    - apk add --no-cache bash
    - ./cicd/run_coverage.sh
    - ./cicd/run_analyze.sh
  artifacts:
    paths:
      - results/
