image: docker:latest

services:
  - docker:dind

test:
  stage: test
  script:
    - apk add --no-cache bash
    - ./cicd/run_coverage_docker.sh
  artifacts:
    paths:
      - results/

analyze:
  stage: test
  script:
    - apk add --no-cache bash
    - ./cicd/run_analyze_docker.sh
  dependencies:
    - test